### ISSUE TITLE
Feedback: Focus should be on as default

### ISSUE THREAD

**Issue by mattcoxonline** [Mojeek/focus-templates#14]
I'm not sure why Focus is disabled as default. Personally, I think it should be an active option in the main menu of the search results page, where today it is not:

![image](https://github.com/Mojeek/focus-templates/assets/673542/c52f2e29-2457-44bb-b6f0-510404c73649)

But _regardless_ of whether it's enabled by default or not, it _should_ be enabled when someone links specifically to a Focus filter. For example, I can link to this search results page with a specific focus filter enabled:

https://www.mojeek.com/search?foc_t=Education%20Websites&q=writing+poetry

And it still doesn't show the navigation option for Focus 😕 (unless I first go to the Focus Dashboard and enable it).

**Comment by PrivacyDingus** [comment]
This one has been raise @mattcoxonline, thinking about how to lead someone to understanding Focus better if they've just arrived via an ```&foc=``` link is a good idea in my eyes.

**Comment by PrivacyDingus** [comment]
This has now been rolled into Mojeek insofar as following a Focus link will automatically add in the Focus dropdown in the UI.
